#!/bin/bash

EEZY_VERSION="v1.2"
PROJECT_FOLDER=$(pwd)
EEZY_FOLDER="${PROJECT_FOLDER}/.eezy"

print_version() {
	echo "Eezy $EEZY_VERSION"
	exit 0
}
not_initialized(){
	echo "Current directory is not an Eezy folder."
	echo "use 'eezy init' to initialize Eezy in this folder."
	exit 0
}
initialize() {
	if [ -d "$EEZY_FOLDER" ]; then 
		echo "Current directory is already an Eezy folder!"
		exit 0
	fi
	echo "Initializing current directory as an Eezy folder."
	mkdir $EEZY_FOLDER
	echo "Finished initializing. Start adding tasks by using 'eezy add-task name-of-new-task'."
	echo "Or use 'eezy help' for more information."
	exit 0
}
error() {
	echo "Use 'eezy help' for information on how to Eezy"
	exit 0
}
help () {
	echo "Eezy - Help"
	echo "Available commands are:"
	echo "	help				- List available commands"
	echo "	version				- Display Eezy version info"
	echo "	init				- Enable Eezy in the current folder"
	echo "	list				- List available Eezy tasks"
	echo "	add-task [taskname]		- Add new Eezy task"
	echo "	edit [taskname] [editor]	- Edit an existing Eezy task, editor argument is optional."
	echo "Use 'eezy' followed by a command or task-name to run that function."
    echo "	e.g.: eezy help"
	exit 0
}
list_tasks() {
	echo "Eezy - Available tasks"
	for entry in "${EEZY_FOLDER}"/*
	do
		echo " - $(basename -- "$entry")"
	done
	exit 0
}
edit_task() {
	local DETECT_RM_REGEX="(\s|;\s*)+rm(\s|;)*|^rm(\s|;)+|^rm$"
	if [ -z "$1" ]; then
		error
	fi
	local filename="$EEZY_FOLDER/$1"
	if [ ! -f $filename ]; then
		echo "Cannot edit task: task with name '$1' doesn't exist!"
		exit 0
	else
		echo "Editing task '$1'"
		shift
		if [ ! -z "$1" ]; then
			if ! command -v "$*" &> /dev/null
			then
				echo "Couldn't find an editor with the name '${*}'."
				exit 1
			elif [[ "$*" =~ $DETECT_RM_REGEX ]]; then
				echo "Detected 'rm' command! Aborting!"
				exit 1
			fi
			$1 $filename
			exit 0
		fi
		${VISUAL:-${EDITOR:-nano}} $filename
		exit 0
	fi
}
add_task() {
	if [ -z "$1" ]; then
		error
	fi
	local filename="$EEZY_FOLDER/$1"
	if [ -f $filename ]; then
		echo "Cannot create task: task with name '$1' already exists!"
	else
		touch $filename
		echo "Task '$1' created."
	fi
}
run_task() {
	if [ -f "$2" ]; then
		local TASK_NAME="$1"
		local TASK_PATH="$2"
		shift; shift; shift;
		source $TASK_PATH
	fi
}
run() {
	if [ -z "$1" ]; then
		error
	fi
	local filename="$EEZY_FOLDER/$1"
	if [ -f $filename ]; then
		echo "Eezy - Running task '$1'"
		local TIMESTART="$SECONDS"
		run_task $1 $filename "$@"
		TOTAL_TIME=`expr $SECONDS - $TIMESTART`
		echo "Eezy - finished running task '$1' in $TOTAL_TIME second(s)."
		exit 0
	else
		echo "Task with name '$1' does not exist!"
		echo "You can add this task by using the command 'eezy add-task $1'"
		error
	fi
}
check_initialization() {
	if [ ! -d "$EEZY_FOLDER" ]; then 
		not_initialized		
	fi
}

if [ $# -eq 0 ]
	then
		error
fi

case "$1" in
	"version")
		print_version
		;;
	
	"help")
		help
		;;
	
	"init")
		initialize
		;;
	
	"list")
		check_initialization
		list_tasks
		;;
	
	"add-task")
		add_task $2
		;;
	
	"edit")
		edit_task $2 $3
		;;
	
	*)
		check_initialization
		run "$@"
		;;
esac
